---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
ansible:
  cfg:
    defaults:
      inject_invocation: true
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: fedora
    image: jrei/systemd-fedora:42
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
verifier:
  name: ansible
