---
- name: config_openldap_overlays | copying ldif files
  copy:
    src: 'files/openldap/overlays/{{ item.path }}'
    dest: '{{ openldap_ldif_tmp_dir }}/{{ item.path }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  become: true
  when: not item.template is defined or not item.template
  with_items: "{{overlay.ldifs}}"

- name: config_openldap_overlays | template ldif files
  template:
    src: 'files/openldap/overlays/{{ item.path }}'
    dest: '{{ openldap_ldif_tmp_dir }}/{{ item.path }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  become: true
  when: item.template is defined and item.template
  with_items: "{{overlay.ldifs}}"

- name: config_openldap_overlays | applying or configuring overlay
  command: "ldap{{item.action}} -Y EXTERNAL -H ldapi:/// -f {{ openldap_ldif_tmp_dir }}/{{ item.path }}"
  ignore_errors: yes #fails on duplicate
  with_items: "{{overlay.ldifs}}"

