---
# tasks file for ansible-openldap
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: config_openldap.yml
  when: openldap_config|bool
