---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
ansible:
  cfg:
    defaults:
      inject_invocation: true
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian12
    image: jrei/systemd-debian:12
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
verifier:
  name: ansible
