---
name: Molecule Test
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 6 * * 0"

concurrency:
  group: molecule-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        scenario:
          - debian12
          - ubuntu2204
          - ubuntu2404
          - fedora
          - rocky9

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
